
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  archives: /archives
  # tags: /tags
  # search: /search
  # about: https://0xff000000.com

local_search:
  enable: true

# Miscelaneous
favicon: /logo.png

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true
#footer
index_page: https://panbinjun.github.io/
main_site: https://panbinjun.github.io/
github: https://github.com/panbinjun
